include:
  - local: .gitlab/ci-shared/template.yml

#############
# Static    #
#############
code-format:
  extends: .full-code-format
  rules:
    - if: $ON_MR
  needs:
    - job: download srsran
  script:
    - &setup_folders mkdir -p ${SRSRANDIR}/plugins && ln -s ${CI_PROJECT_DIR} ${SRSRANDIR}/plugins/${CI_PROJECT_NAME}
    - cd ${SRSRANDIR}/plugins/${CI_PROJECT_NAME}
    - full_code_format

include-guards:
  extends: .include-guards
  needs:
    - job: download srsran
  script:
    - *setup_folders
    - cd ${SRSRANDIR}/plugins/${CI_PROJECT_NAME}
    - include-guards-check

#########
# Build #
#########
.build_with_plugin:
  extends: .build_and_unit
  stage: build
  variables:
    ENABLE_PLUGINS: "True"
  script:
    - *setup_folders
    - build_srsran
    - launch_tests_srsran
  needs:
    - job: download srsran
    - job: builder version
