cu_up:
  f1u:
    socket:
      - 
        # Default socket. If the DRB's 5QI does not have a socket assigned,
        # this socket will be used. At least one default socket is required. 
        bind_addr: 127.0.3.1  # Address that the F1-U socket will bind to.
        #ext_addr: 8.8.8.8    # Address that is reported as the F1-U bind address.
                              # If empty, the real bind address is used.
        udp:
          max_rx_msgs: 256    # maximum packets read from the socket in a single syscall.
          pool_threshold: 0.9 # Pool occupancy threshold, after which packets are dropped.

      - 
        five_qi: 7            # Socket used for a specific 5QI.  
        bind_addr: 127.0.3.2  # Address that the F1-U socket will bind to.
        #ext_addr: 8.8.8.8    # Address that is reported as the F1-U bind address.
                              # If empty, the real bind address is used.
        udp:
          max_rx_msgs: 256    # maximum packets read from the socket in a single syscall.
          pool_threshold: 0.9 # Pool occupancy threshold, after which packets are dropped.
